name: Build a Nodejs App and push to Docker hub

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  build_and_push:
    name: countious integration
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: ['18.x', '20.x'] 

    steps:
      - name: checkout repository
        uses: actions/checkout@4
      - name: Set up Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version}}
      - name: install dependencies and build frontend
        run: |
         cd dive-react-app
         npm install
         npm run lint
         npm run build
     
  
